# Generated by Django 3.1.7 on 2021-09-28 19:01

import VintageJewelry_Store.apps.validation
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=60, validators=[VintageJewelry_Store.apps.validation.validate_name])),
                ('last_name', models.CharField(max_length=60, validators=[VintageJewelry_Store.apps.validation.validate_name])),
                ('email', models.EmailField(max_length=180, unique=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=60, validators=[VintageJewelry_Store.apps.validation.validate_name])),
                ('street', models.CharField(blank=True, max_length=60)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
