# Generated by Django 3.1.7 on 2021-09-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_products',
        ),
    ]
