# Generated by Django 3.1.7 on 2021-09-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0003_remove_order_selected_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_products',
            field=models.ManyToManyField(through='orders.OrderProducts', to='products.Product'),
        ),
    ]
