# Generated by Django 3.1.7 on 2021-09-28 19:27

import VintageJewelry_Store.apps.validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[VintageJewelry_Store.apps.validation.validate_name])),
                ('brand_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[VintageJewelry_Store.apps.validation.validate_price])),
                ('description', models.TextField(blank=True)),
                ('material', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
