# Generated by Django 3.1.7 on 2021-10-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner_id',
        ),
    ]
